'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState, type FormEvent } from 'react';
import { getActiveDefinitions, productionApi, validateProductionPlan } from '@/lib/production';
import { getPurchaseCatalog } from '@/lib/purchases';
import { formatQuantity, type BaseUnit } from '@/lib/product-quantity';
import { useSalesResource } from '../../../sales/orders/_components/use-sales-resource';
import { ProductionShell, ProductionError, ProductionLoading, productionButton, productionCard, productionInput, productionSecondary } from '../../_components/production-ui';

export default function ProductionPlan({ initialDefinitionId }: { initialDefinitionId?: number }) {
  const definitions = useSalesResource(getActiveDefinitions); const catalog = useSalesResource(getPurchaseCatalog); const router = useRouter();
  const [definitionId, setDefinitionId] = useState(initialDefinitionId ? String(initialDefinitionId) : ''); const [plannedQuantity, setPlannedQuantity] = useState(''); const [notes, setNotes] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const definition = definitions.data?.find(item => item.id === Number(definitionId)); const products = catalog.data ?? []; const output = products.find(product => product.id === definition?.outputProductId); const name = (id: number) => products.find(product => product.id === id)?.name ?? `Product #${id}`;
  const scale = definition && Number(plannedQuantity) > 0 ? Number(plannedQuantity) / definition.outputQuantity : 0;
  const submit = async (event: FormEvent) => { event.preventDefault(); const input = { definitionId: Number(definitionId), plannedQuantity: Number(plannedQuantity), ...(notes.trim() ? { notes: notes.trim() } : {}) }; const validation = validateProductionPlan(input, definition, output); if (validation) { setError(validation); return; } setBusy(true); setError(''); try { const order = await productionApi.createOrder(input); router.push(`/dashboard/production/orders/${order.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to plan production.'); setBusy(false); } };
  return <ProductionShell title="Plan Production" description="Planning calculates material requirements but does not change stock.">
    {definitions.loading || catalog.loading ? <ProductionLoading /> : definitions.error || catalog.error ? <ProductionError message={definitions.error ?? catalog.error ?? 'Unable to load planning data.'} retry={() => { definitions.reload(); catalog.reload(); }} /> : <form onSubmit={submit} className="space-y-5">{error && <ProductionError message={error} />}<fieldset disabled={busy} className="space-y-5 disabled:opacity-70"><section className={`${productionCard} grid gap-4 sm:grid-cols-2`}><label className="space-y-1 text-sm">Active definition *<select required className={productionInput} value={definitionId} onChange={event => { setDefinitionId(event.target.value); setPlannedQuantity(''); }}><option value="">Select recipe / BOM</option>{definitions.data?.map(item => <option key={item.id} value={item.id}>{item.name} · v{item.version} · {name(item.outputProductId)}</option>)}</select></label><label className="space-y-1 text-sm">Planned finished quantity{definition ? ` (${definition.outputUnit})` : ''} *<input required type="number" className={productionInput} min={output?.quantityPrecision != null ? 10 ** -output.quantityPrecision : 0.001} step={output?.quantityPrecision != null ? 10 ** -output.quantityPrecision : 0.001} value={plannedQuantity} onChange={event => setPlannedQuantity(event.target.value)} /></label><label className="space-y-1 text-sm sm:col-span-2">Planning notes<textarea className={productionInput} rows={3} maxLength={1000} value={notes} onChange={event => setNotes(event.target.value)} /></label></section>{definition && <section className={`${productionCard} overflow-x-auto`}><div className="mb-4"><h2 className="font-semibold">Planned materials</h2><p className="text-sm text-slate-500">Preview scaled from {formatQuantity(definition.outputQuantity, definition.outputUnit)} definition output. The saved order will display backend-calculated amounts.</p></div><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500 dark:border-slate-700"><tr><th className="px-3 py-3">Material</th><th className="px-3 py-3">Planned amount</th></tr></thead><tbody className="divide-y dark:divide-slate-700">{definition.components.map(component => <tr key={component.id}><td className="px-3 py-4">{name(component.productId)}</td><td className="px-3 py-4">{scale ? formatQuantity(component.quantity * scale, component.baseUnit as BaseUnit) : '—'}</td></tr>)}</tbody></table></section>}<div className="flex justify-end gap-3"><Link className={productionSecondary} href="/dashboard/production/orders">Cancel</Link><button className={productionButton} disabled={busy || !definition}>{busy ? 'Planning…' : 'Create Planned Order'}</button></div></fieldset></form>}
  </ProductionShell>;
}
