'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useCallback, useState, type FormEvent } from 'react';
import { productionApi, validateCompletion, type CompleteProductionOrderInput } from '@/lib/production';
import { getPurchaseCatalog } from '@/lib/purchases';
import { formatQuantity } from '@/lib/product-quantity';
import { useDurableInventoryMutation } from '@/app/components/useDurableInventoryMutation';
import { useSalesResource } from '../../../sales/orders/_components/use-sales-resource';
import { ProductionShell, ProductionError, ProductionLoading, ProductionStatusBadge, productionButton, productionCard, productionInput, productionSecondary } from '../../_components/production-ui';

export default function ProductionComplete({ id }: { id: number }) {
  const order = useSalesResource(useCallback(() => productionApi.getOrder(id), [id])); const catalog = useSalesResource(getPurchaseCatalog); const router = useRouter();
  if (order.loading || catalog.loading) return <ProductionShell title={`Complete PROD-${id}`}><ProductionLoading /></ProductionShell>;
  if (order.error || catalog.error || !order.data) return <ProductionShell title={`Complete PROD-${id}`}><ProductionError message={order.error ?? catalog.error ?? 'Production order unavailable.'} retry={() => { order.reload(); catalog.reload(); }} /></ProductionShell>;
  return <CompleteForm key={`${id}:${order.data.status}`} order={order.data} products={catalog.data ?? []} onSuccess={() => router.replace(`/dashboard/production/orders/${id}`)} />;
}

function CompleteForm({ order, products, onSuccess }: { order: Awaited<ReturnType<typeof productionApi.getOrder>>; products: Awaited<ReturnType<typeof getPurchaseCatalog>>; onSuccess: () => void }) {
  const [actualQuantity, setActualQuantity] = useState(String(order.plannedQuantity)); const [materials, setMaterials] = useState(() => Object.fromEntries(order.materials.map(material => [material.productId, String(material.plannedQuantity)]))); const [notes, setNotes] = useState(order.notes ?? ''); const [validationError, setValidationError] = useState('');
  const operation = useDurableInventoryMutation<CompleteProductionOrderInput, typeof order>(`production-complete:${order.id}`, (payload, key) => productionApi.completeOrder(order.id, payload, key), onSuccess);
  const name = (id: number) => products.find(product => product.id === id)?.name ?? `Product #${id}`; const output = products.find(product => product.id === order.outputProductId);
  const submit = (event: FormEvent) => { event.preventDefault(); const input = { actualQuantity: Number(actualQuantity), materials: order.materials.map(material => ({ productId: material.productId, quantity: Number(materials[material.productId]) })), ...(notes.trim() ? { notes: notes.trim() } : {}) }; const validation = validateCompletion(order, input, products); if (validation) { setValidationError(validation); return; } setValidationError(''); operation.run(input); };
  if (order.status !== 'PLANNED' && !operation.pending) return <ProductionShell title={`Complete PROD-${order.id}`} order={{ id: order.id, label: `PROD-${order.id}` }}><ProductionError message="This production order is already completed. No further stock action is allowed." /><Link href={`/dashboard/production/orders/${order.id}`} className={productionSecondary}>Back to order</Link></ProductionShell>;
  return <ProductionShell title={`Complete PROD-${order.id}`} description="Confirm finished output and actual material use. Stock changes are atomic." order={{ id: order.id, label: `PROD-${order.id}` }}>
    {(validationError || operation.error) && <ProductionError message={validationError || operation.error} />}
    {operation.pending && <section className={`${productionCard} space-y-3 border-amber-300 bg-amber-50 dark:border-amber-800 dark:bg-amber-950`}><h2 className="font-semibold">Saved completion awaiting confirmation</h2><p className="text-sm">The exact request and idempotency key are saved in this browser tab. Retry it unchanged so materials and finished stock cannot be posted twice.</p><button type="button" className={productionButton} disabled={operation.busy} onClick={operation.retry}>{operation.busy ? 'Retrying…' : 'Retry Saved Completion'}</button></section>}
    <form onSubmit={submit} className="space-y-5"><fieldset disabled={!operation.ready || operation.busy || !!operation.pending} className="space-y-5 disabled:opacity-70"><section className={`${productionCard} grid gap-4 sm:grid-cols-3`}><div><p className="text-xs uppercase text-slate-500">Status</p><div className="mt-2"><ProductionStatusBadge status={order.status} /></div></div><div><p className="text-xs uppercase text-slate-500">Planned output</p><p className="mt-2 font-semibold">{formatQuantity(order.plannedQuantity, order.outputUnit)}</p></div><label className="space-y-1 text-sm">Actual finished quantity ({order.outputUnit}) *<input required type="number" aria-label="Actual finished quantity" className={productionInput} min={output?.quantityPrecision != null ? 10 ** -output.quantityPrecision : 0.001} step={output?.quantityPrecision != null ? 10 ** -output.quantityPrecision : 0.001} value={actualQuantity} onChange={event => setActualQuantity(event.target.value)} /></label></section>
      <section className={`${productionCard} space-y-4`}><div><h2 className="font-semibold">Actual material consumption</h2><p className="text-sm text-slate-500">Every planned material is required exactly once. Zero is allowed, but at least one material must be consumed.</p></div>{order.materials.map(material => { const product = products.find(item => item.id === material.productId); return <div key={material.productId} className="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-2 dark:border-slate-700"><div><p className="font-semibold">{name(material.productId)}</p><p className="text-sm text-slate-500">Planned: {formatQuantity(material.plannedQuantity, material.baseUnit)}</p></div><label className="space-y-1 text-sm">Actual quantity ({material.baseUnit}) *<input required type="number" aria-label={`Actual quantity for ${name(material.productId)}`} className={productionInput} min="0" step={product?.quantityPrecision != null ? 10 ** -product.quantityPrecision : 0.001} value={materials[material.productId] ?? ''} onChange={event => setMaterials(previous => ({ ...previous, [material.productId]: event.target.value }))} /></label></div>; })}<label className="block space-y-1 text-sm">Completion notes<textarea className={productionInput} rows={3} maxLength={1000} value={notes} onChange={event => setNotes(event.target.value)} placeholder="Explain yield or material variance" /></label></section>
      <div className="flex justify-end gap-3"><Link href={`/dashboard/production/orders/${order.id}`} className={productionSecondary}>Cancel</Link><button className={productionButton} disabled={operation.busy}>{operation.busy ? 'Completing…' : 'Complete & Post Stock'}</button></div></fieldset></form>
  </ProductionShell>;
}
